config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :users, only: [:show]
  get '/dashboard', to: "dashboard#index"
  resources :repos, only: [:index]
  resources :followings, only: [:index]
  get '/following', to: 'followings#show'
  get '/recent_activity', to: 'recent_activity#index'
  resources :organizations, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit
  attr_reader :repo_name,
              :sha_key,
              :message,
              :author,
              :created_at

  def initialize(info)
    @author = info[:author][:login]
    @repo_name = info[:repository][:full_name]
    @sha_key = info[:sha]
    @message = info[:commit][:message]
    @created_at = DateTime.parse(info[:commit][:author][:date])
  end
  
end

app/models/follower.rb
class Follower
  attr_reader :login,
              :image

  def initialize(follower_info)
    @login = follower_info[:login]
    @image = follower_info[:avatar_url]
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :login,
              :image,
              :url,
              :token

  def initialize(login, image, url, token = nil)
    @login = login
    @image = image
    @url = url
    @token = token
  end
  
end

app/models/organization.rb
class Organization
  attr_reader :login,
              :url,
              :description
              
  def initialize(org_info)
    @login = org_info[:login]
    @url = org_info[:url]
    @description = org_info[:description]
  end
end

app/models/presenter.rb
class Presenter
  attr_reader :service

  def initialize(github_user)
    @service = GithubService.new(github_user)
  end

  def starred_repos
    @service.starred_repos.map do |raw_repo|
      Repository.new(raw_repo)
    end
  end

  def followers
    @service.followers.map do |follower|
      GithubUser.new(follower[:login], follower[:avatar_url], follower[:url])
    end
  end

  def followings
    @service.followings.map do |following|
      GithubUser.new(following[:login], following[:avatar_url], following[:url])
    end
  end

  def repositories
    @service.repositories.map do |repo_info|
      Repository.new(repo_info)
    end
  end

  def organizations
    @service.organizations.map do |org_info|
      Organization.new(org_info)
    end
  end

  def recent_commits
    @service.recent_commits.pop(10).reverse.map do |commit_info|
      Commit.new(commit_info)
    end
  end
end

app/models/repository.rb
class Repository
  attr_reader :name,
              :owner,
              :url,
              :created_at,
              :updated_at

  def initialize(raw_repo)
    @name = raw_repo[:name]
    @owner = raw_repo[:owner][:login]
    @url = raw_repo[:url]
    @created_at = raw_repo[:created_at]
    @updated_at = raw_repo[:updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth[:provider]
      user.uid = auth[:uid]
      user.name = auth[:info][:name]
      user.token = auth[:credentials][:token]
      user.image = auth[:extra][:raw_info][:avatar_url]
      user.login = auth[:extra][:raw_info][:login]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @presenter = Presenter.new(current_user)
  end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @presenter = Presenter.new(current_user)
  end

  def show
    @presenter = Presenter.new(GithubUser.new(params[:login], nil, nil, current_user.token))
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @presenter = Presenter.new(current_user)
  end

  def show
    @presenter = Presenter.new(GithubUser.new(params[:login], nil, nil, current_user.token))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @presenter = Presenter.new(current_user)
  end

end

app/controllers/recent_activity_controller.rb
class RecentActivityController < ApplicationController
  def index
    @presenter = Presenter.new(current_user)
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    @presenter = Presenter.new(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth[:provider], auth[:uid]) || User.create_with_omniauth(auth)
    user.update(token: auth["credentials"]["token"])
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<% if current_user %>
<img src="<%= current_user.image %>" alt="avatar">
<div class="starred">Starred Repos <%= @presenter.starred_repos.length %></div>
<div class="followers">Followers: <%= @presenter.followers.length %></div>
<div class="following"><%= link_to 'Following:', '/followings' %> <%= @presenter.followings.length %></div>
<%= link_to 'Recent Activity', '/recent_activity' %></br>
<%= link_to 'Repositories', '/repos' %>
<%= link_to 'Organizations', '/organizations' %>
<% end %>

app/views/followings/index.html.erb
<h2><%= current_user.name %>'s Followers</h2>
<% @presenter.followings.each do |following| %>
<ul class="following">
  <img src="<%= following.image %>" alt="" class="following-image">
  <%= link_to following.login, following_path(login: following.login), class: 'following-login'%>
</ul>
<% end %>

app/views/followings/show.html.erb
<h1><%= @presenter.service.login %>'s Recent Activity</h1>
<% @presenter.recent_commits.each do |commit| %>
  <ul class="commit">
    <li class="commit-author">Author: <%= commit.author %></li>
    <li class="commit-repo-name">Repository: <%= commit.repo_name %></li>
    <li class="commit-sha">Sha Key: <%= commit.sha_key %></li>
    <li class="commit-message">Message: <%= commit.message %></li>
    <li class="commit-created-at">Created At: <%= commit.created_at.strftime("%Y/%m/%d at %I:%M%p") %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
    <h1>Welcome, <%= current_user.name %></h1>
    <%= link_to "Logout", "/logout" %>
    <% else %>
      <%= link_to "Login", "/auth/github" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/organizations/index.html.erb
<% @presenter.organizations.each do |org| %>
  <ul class="organization">
    <li class="org-login"><%= org.login %></li>
    <li class="org-url"><%= org.url %></li>
    <li class="org-description"><%= org.description %></li>
  </ul>
<% end %>

app/views/recent_activity/index.html.erb
<h1><%= current_user.name %>'s Recent Commits</h1>
<% @presenter.recent_commits.each do |commit| %>
<ul class="commit">
  <li class="commit-author">Author: <%= commit.author %></li>
  <li class="commit-repo-name">Repository: <%= commit.repo_name %></li>
  <li class="commit-sha">Sha Key: <%= commit.sha_key %></li>
  <li class="commit-message">Message: <%= commit.message %></li>
  <li class="commit-created-at">Created At: <%= commit.created_at.strftime("%Y/%m/%d at %I:%M%p") %></li>
</ul>
<% end %>

app/views/repos/index.html.erb
<h1><%= current_user.name %>'s Repositories</h1>


<% @presenter.repositories.each do |repo| %>
<ul class="repo">
  <li class="repo-name"><%= repo.name %></li>
  <li class="repo-url"><%= link_to repo.url, repo.url %></li>
</ul>
<% end %>